
--  DDL for Table ADDRESS
--------------------------------------------------------

  CREATE TABLE "BILGEADAM"."ADDRESS" 
   (	"ADDRESSID" NUMBER, 
	"ADDRESSLINE1" VARCHAR2(60 BYTE), 
	"ADDRESSLINE2" VARCHAR2(60 BYTE), 
	"CITY" VARCHAR2(30 BYTE), 
	"STATEPROVINCEID" NUMBER, 
	"POSTALCODE" VARCHAR2(15 BYTE), 
	"MODIFIEDDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CURRENCY
--------------------------------------------------------

  CREATE TABLE "BILGEADAM"."CURRENCY" 
   (	"CURRENCYCODE" VARCHAR2(5 BYTE), 
	"NAME" VARCHAR2(50 BYTE), 
	"MODIFIEDDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "BILGEADAM"."CUSTOMER" 
   (	"CUSTOMERID" NUMBER, 
	"PERSONID" NUMBER, 
	"STOREID" NUMBER, 
	"TERRITORYID" NUMBER, 
	"ACCOUNTNUMBER" VARCHAR2(10 BYTE), 
	"MODIFIEDDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEPARTMENT
--------------------------------------------------------

  CREATE TABLE "BILGEADAM"."DEPARTMENT" 
   (	"DEPARTMENTID" NUMBER(38,0), 
	"NAME" VARCHAR2(50 BYTE), 
	"GROUPNAME" VARCHAR2(50 BYTE), 
	"MODIFIEDDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMAILADDRESS
--------------------------------------------------------

  CREATE TABLE "BILGEADAM"."EMAILADDRESS" 
   (	"BUSINESSENTITYID" NUMBER(*,0), 
	"EMAILADDRESSID" NUMBER(*,0), 
	"EMAILADDRESS" NVARCHAR2(100), 
	"MODIFIEDDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "BILGEADAM"."EMPLOYEE" 
   (	"BUSINESSENTITYID" NUMBER, 
	"NATIONALIDNUMBER" VARCHAR2(20 BYTE), 
	"LOGINID" VARCHAR2(256 BYTE), 
	"JOBTITLE" VARCHAR2(50 BYTE), 
	"BIRTHDATE" DATE, 
	"MARITALSTATUS" VARCHAR2(20 BYTE), 
	"GENDER" VARCHAR2(20 BYTE), 
	"HIREDATE" DATE, 
	"VACATIONHOURS" NUMBER, 
	"MODIFIEDDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PERSON
--------------------------------------------------------

  CREATE TABLE "BILGEADAM"."PERSON" 
   (	"BUSINESSENTITYID" NUMBER(*,0), 
	"PERSONTYPE" VARCHAR2(20 BYTE), 
	"NAMESTYLE" NUMBER(1,0), 
	"TITLE" VARCHAR2(8 BYTE), 
	"FIRSTNAME" VARCHAR2(50 BYTE), 
	"MIDDLENAME" VARCHAR2(50 BYTE), 
	"LASTNAME" VARCHAR2(50 BYTE), 
	"SUFFIX" VARCHAR2(10 BYTE), 
	"EMAILPROMOTION" NUMBER(*,0), 
	"MODIFIEDDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PERSONPHONE
--------------------------------------------------------

  CREATE TABLE "BILGEADAM"."PERSONPHONE" 
   (	"BUSINESSENTITYID" NUMBER(38,0), 
	"PHONENUMBER" VARCHAR2(25 BYTE), 
	"PHONENUMBERTYPEID" NUMBER(38,0), 
	"MODIFIEDDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCT
--------------------------------------------------------

  CREATE TABLE "BILGEADAM"."PRODUCT" 
   (	"PRODUCTID" NUMBER, 
	"NAME" VARCHAR2(50 BYTE), 
	"PRODUCTNUMBER" VARCHAR2(25 BYTE), 
	"COLOR" VARCHAR2(15 BYTE), 
	"SAFETYSTOCKLEVEL" NUMBER, 
	"REORDERPOINT" NUMBER, 
	"STANDARDCOST" NUMBER(19,4), 
	"LISTPRICE" NUMBER(19,4), 
	"SIZED" VARCHAR2(5 BYTE), 
	"WEIGHT" NUMBER(8,2), 
	"DAYSTOMANUFACTURE" NUMBER, 
	"PRODUCTLINE" VARCHAR2(20 BYTE), 
	"CLASS" VARCHAR2(20 BYTE), 
	"STYLE" VARCHAR2(20 BYTE), 
	"PRODUCTSUBCATEGORYID" NUMBER, 
	"PRODUCTMODELID" NUMBER, 
	"SELLSTARTDATE" DATE, 
	"SELLENDDATE" DATE, 
	"DISCONTINUEDDATE" DATE, 
	"MODIFIEDDATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCTCATEGORY
--------------------------------------------------------

  CREATE TABLE "BILGEADAM"."PRODUCTCATEGORY" 
   (	"PRODUCTCATEGORYID" NUMBER, 
	"NAME" VARCHAR2(50 BYTE), 
	"MODIFIEDDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCTMODEL
--------------------------------------------------------

  CREATE TABLE "BILGEADAM"."PRODUCTMODEL" 
   (	"PRODUCTMODELID" NUMBER, 
	"NAME" VARCHAR2(50 BYTE), 
	"MODIFIEDDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCTSUBCATEGORY
--------------------------------------------------------

  CREATE TABLE "BILGEADAM"."PRODUCTSUBCATEGORY" 
   (	"PRODUCTSUBCATEGORYID" NUMBER, 
	"PRODUCTCATEGORYID" NUMBER, 
	"NAME" VARCHAR2(50 BYTE), 
	"MODIFIEDDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SALESORDERHEADER
--------------------------------------------------------

  CREATE TABLE "BILGEADAM"."SALESORDERHEADER" 
   (	"SALESORDERID" NUMBER, 
	"REVISIONNUMBER" NUMBER(5,0), 
	"ORDERDATE" DATE, 
	"DUEDATE" DATE, 
	"SHIPDATE" DATE, 
	"STATUS" NUMBER(5,0), 
	"SALESORDERNUMBER" VARCHAR2(25 BYTE), 
	"PURCHASEORDERNUMBER" VARCHAR2(25 BYTE), 
	"ACCOUNTNUMBER" VARCHAR2(15 BYTE), 
	"CUSTOMERID" NUMBER, 
	"SALESPERSONID" NUMBER, 
	"TERRITORYID" NUMBER, 
	"CREDITCARDID" NUMBER, 
	"CREDITCARDAPPROVALCODE" VARCHAR2(15 BYTE), 
	"CURRENCYRATEID" NUMBER, 
	"SUBTOTAL" NUMBER(19,4), 
	"TAXAMT" NUMBER(19,4), 
	"FREIGHT" NUMBER(19,4), 
	"TOTALDUE" NUMBER(19,4), 
	"MODIFIEDDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SALESPERSON
--------------------------------------------------------

  CREATE TABLE "BILGEADAM"."SALESPERSON" 
   (	"BUSINESSENTITYID" NUMBER, 
	"TERRITORYID" NUMBER, 
	"SALESQUOTA" NUMBER(19,4), 
	"BONUS" NUMBER(19,4), 
	"COMMISSIONPCT" NUMBER(10,4), 
	"SALESYTD" NUMBER(19,4), 
	"SALESLASTYEAR" NUMBER(19,4), 
	"MODIFIEDDATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SALESTERRITORY
--------------------------------------------------------

  CREATE TABLE "BILGEADAM"."SALESTERRITORY" 
   (	"TERRITORYID" NUMBER, 
	"NAME" VARCHAR2(50 BYTE), 
	"COUNTRYREGÝONCODE" VARCHAR2(3 BYTE), 
	"GROUPS" VARCHAR2(50 BYTE), 
	"SALESYTD" NUMBER(19,4), 
	"SALESLASTYEAR" NUMBER(19,4), 
	"COSTYTD" NUMBER(19,4), 
	"COSTLASTYEAR" NUMBER(19,4), 
	"MODIFIEDDATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STORE
--------------------------------------------------------

  CREATE TABLE "BILGEADAM"."STORE" 
   (	"BUSINESSENTITYID" NUMBER, 
	"NAME" VARCHAR2(50 BYTE), 
	"SALESPERSONID" NUMBER, 
	"MODIFIEDDATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

--  DDL for Index Address_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BILGEADAM"."Address_PK" ON "BILGEADAM"."ADDRESS" ("ADDRESSID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index Currency_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BILGEADAM"."Currency_PK" ON "BILGEADAM"."CURRENCY" ("CURRENCYCODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index Customer_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BILGEADAM"."Customer_PK" ON "BILGEADAM"."CUSTOMER" ("CUSTOMERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index Department_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BILGEADAM"."Department_PK" ON "BILGEADAM"."DEPARTMENT" ("DEPARTMENTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EmailAddress_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BILGEADAM"."EmailAddress_PK" ON "BILGEADAM"."EMAILADDRESS" ("BUSINESSENTITYID", "EMAILADDRESSID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index Employee_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BILGEADAM"."Employee_PK" ON "BILGEADAM"."EMPLOYEE" ("BUSINESSENTITYID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index Person_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BILGEADAM"."Person_PK" ON "BILGEADAM"."PERSON" ("BUSINESSENTITYID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ProductCategory_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BILGEADAM"."ProductCategory_PK" ON "BILGEADAM"."PRODUCTCATEGORY" ("PRODUCTCATEGORYID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ProductModel_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BILGEADAM"."ProductModel_PK" ON "BILGEADAM"."PRODUCTMODEL" ("PRODUCTMODELID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ProductSubcategory_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BILGEADAM"."ProductSubcategory_PK" ON "BILGEADAM"."PRODUCTSUBCATEGORY" ("PRODUCTSUBCATEGORYID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index Product_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BILGEADAM"."Product_PK" ON "BILGEADAM"."PRODUCT" ("PRODUCTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SalesOrderHeader_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BILGEADAM"."SalesOrderHeader_PK" ON "BILGEADAM"."SALESORDERHEADER" ("SALESORDERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SalesPerson_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BILGEADAM"."SalesPerson_PK" ON "BILGEADAM"."SALESPERSON" ("BUSINESSENTITYID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SalesTerritory_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BILGEADAM"."SalesTerritory_PK" ON "BILGEADAM"."SALESTERRITORY" ("TERRITORYID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ADDRESS
--------------------------------------------------------

  ALTER TABLE "BILGEADAM"."ADDRESS" ADD CONSTRAINT "Address_PK" PRIMARY KEY ("ADDRESSID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BILGEADAM"."ADDRESS" MODIFY ("MODIFIEDDATE" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."ADDRESS" MODIFY ("POSTALCODE" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."ADDRESS" MODIFY ("STATEPROVINCEID" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."ADDRESS" MODIFY ("CITY" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."ADDRESS" MODIFY ("ADDRESSLINE1" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."ADDRESS" MODIFY ("ADDRESSID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CURRENCY
--------------------------------------------------------

  ALTER TABLE "BILGEADAM"."CURRENCY" ADD CONSTRAINT "Currency_PK" PRIMARY KEY ("CURRENCYCODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BILGEADAM"."CURRENCY" MODIFY ("MODIFIEDDATE" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."CURRENCY" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."CURRENCY" MODIFY ("CURRENCYCODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "BILGEADAM"."CUSTOMER" ADD CONSTRAINT "Customer_PK" PRIMARY KEY ("CUSTOMERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BILGEADAM"."CUSTOMER" MODIFY ("MODIFIEDDATE" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."CUSTOMER" MODIFY ("ACCOUNTNUMBER" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."CUSTOMER" MODIFY ("CUSTOMERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEPARTMENT
--------------------------------------------------------

  ALTER TABLE "BILGEADAM"."DEPARTMENT" ADD CONSTRAINT "Department_PK" PRIMARY KEY ("DEPARTMENTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BILGEADAM"."DEPARTMENT" MODIFY ("MODIFIEDDATE" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."DEPARTMENT" MODIFY ("GROUPNAME" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."DEPARTMENT" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."DEPARTMENT" MODIFY ("DEPARTMENTID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMAILADDRESS
--------------------------------------------------------

  ALTER TABLE "BILGEADAM"."EMAILADDRESS" ADD CONSTRAINT "EmailAddress_PK" PRIMARY KEY ("BUSINESSENTITYID", "EMAILADDRESSID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BILGEADAM"."EMAILADDRESS" MODIFY ("MODIFIEDDATE" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."EMAILADDRESS" MODIFY ("EMAILADDRESSID" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."EMAILADDRESS" MODIFY ("BUSINESSENTITYID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "BILGEADAM"."EMPLOYEE" ADD CONSTRAINT "Employee_PK" PRIMARY KEY ("BUSINESSENTITYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BILGEADAM"."EMPLOYEE" MODIFY ("MODIFIEDDATE" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."EMPLOYEE" MODIFY ("VACATIONHOURS" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."EMPLOYEE" MODIFY ("HIREDATE" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."EMPLOYEE" MODIFY ("GENDER" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."EMPLOYEE" MODIFY ("MARITALSTATUS" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."EMPLOYEE" MODIFY ("BIRTHDATE" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."EMPLOYEE" MODIFY ("JOBTITLE" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."EMPLOYEE" MODIFY ("LOGINID" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."EMPLOYEE" MODIFY ("NATIONALIDNUMBER" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."EMPLOYEE" MODIFY ("BUSINESSENTITYID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERSON
--------------------------------------------------------

  ALTER TABLE "BILGEADAM"."PERSON" ADD CONSTRAINT "Person_PK" PRIMARY KEY ("BUSINESSENTITYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BILGEADAM"."PERSON" MODIFY ("MODIFIEDDATE" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."PERSON" MODIFY ("EMAILPROMOTION" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."PERSON" MODIFY ("LASTNAME" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."PERSON" MODIFY ("FIRSTNAME" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."PERSON" MODIFY ("NAMESTYLE" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."PERSON" MODIFY ("PERSONTYPE" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."PERSON" MODIFY ("BUSINESSENTITYID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERSONPHONE
--------------------------------------------------------

  ALTER TABLE "BILGEADAM"."PERSONPHONE" MODIFY ("MODIFIEDDATE" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."PERSONPHONE" MODIFY ("PHONENUMBERTYPEID" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."PERSONPHONE" MODIFY ("PHONENUMBER" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."PERSONPHONE" MODIFY ("BUSINESSENTITYID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "BILGEADAM"."PRODUCT" ADD CONSTRAINT "Product_PK" PRIMARY KEY ("PRODUCTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BILGEADAM"."PRODUCT" MODIFY ("MODIFIEDDATE" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."PRODUCT" MODIFY ("SELLSTARTDATE" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."PRODUCT" MODIFY ("DAYSTOMANUFACTURE" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."PRODUCT" MODIFY ("LISTPRICE" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."PRODUCT" MODIFY ("STANDARDCOST" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."PRODUCT" MODIFY ("REORDERPOINT" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."PRODUCT" MODIFY ("SAFETYSTOCKLEVEL" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."PRODUCT" MODIFY ("PRODUCTNUMBER" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."PRODUCT" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."PRODUCT" MODIFY ("PRODUCTID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCTCATEGORY
--------------------------------------------------------

  ALTER TABLE "BILGEADAM"."PRODUCTCATEGORY" ADD CONSTRAINT "ProductCategory_PK" PRIMARY KEY ("PRODUCTCATEGORYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BILGEADAM"."PRODUCTCATEGORY" MODIFY ("MODIFIEDDATE" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."PRODUCTCATEGORY" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."PRODUCTCATEGORY" MODIFY ("PRODUCTCATEGORYID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCTMODEL
--------------------------------------------------------

  ALTER TABLE "BILGEADAM"."PRODUCTMODEL" ADD CONSTRAINT "ProductModel_PK" PRIMARY KEY ("PRODUCTMODELID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BILGEADAM"."PRODUCTMODEL" MODIFY ("MODIFIEDDATE" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."PRODUCTMODEL" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."PRODUCTMODEL" MODIFY ("PRODUCTMODELID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCTSUBCATEGORY
--------------------------------------------------------

  ALTER TABLE "BILGEADAM"."PRODUCTSUBCATEGORY" ADD CONSTRAINT "ProductSubcategory_PK" PRIMARY KEY ("PRODUCTSUBCATEGORYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BILGEADAM"."PRODUCTSUBCATEGORY" MODIFY ("MODIFIEDDATE" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."PRODUCTSUBCATEGORY" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."PRODUCTSUBCATEGORY" MODIFY ("PRODUCTCATEGORYID" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."PRODUCTSUBCATEGORY" MODIFY ("PRODUCTSUBCATEGORYID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SALESORDERHEADER
--------------------------------------------------------

  ALTER TABLE "BILGEADAM"."SALESORDERHEADER" ADD CONSTRAINT "SalesOrderHeader_PK" PRIMARY KEY ("SALESORDERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BILGEADAM"."SALESORDERHEADER" MODIFY ("MODIFIEDDATE" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."SALESORDERHEADER" MODIFY ("TOTALDUE" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."SALESORDERHEADER" MODIFY ("FREIGHT" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."SALESORDERHEADER" MODIFY ("TAXAMT" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."SALESORDERHEADER" MODIFY ("SUBTOTAL" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."SALESORDERHEADER" MODIFY ("CUSTOMERID" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."SALESORDERHEADER" MODIFY ("SALESORDERNUMBER" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."SALESORDERHEADER" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."SALESORDERHEADER" MODIFY ("DUEDATE" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."SALESORDERHEADER" MODIFY ("ORDERDATE" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."SALESORDERHEADER" MODIFY ("REVISIONNUMBER" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."SALESORDERHEADER" MODIFY ("SALESORDERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SALESPERSON
--------------------------------------------------------

  ALTER TABLE "BILGEADAM"."SALESPERSON" ADD CONSTRAINT "SalesPerson_PK" PRIMARY KEY ("BUSINESSENTITYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BILGEADAM"."SALESPERSON" MODIFY ("MODIFIEDDATE" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."SALESPERSON" MODIFY ("SALESLASTYEAR" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."SALESPERSON" MODIFY ("SALESYTD" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."SALESPERSON" MODIFY ("COMMISSIONPCT" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."SALESPERSON" MODIFY ("BONUS" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."SALESPERSON" MODIFY ("BUSINESSENTITYID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SALESTERRITORY
--------------------------------------------------------

  ALTER TABLE "BILGEADAM"."SALESTERRITORY" ADD CONSTRAINT "SalesTerritory_PK" PRIMARY KEY ("TERRITORYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BILGEADAM"."SALESTERRITORY" MODIFY ("MODIFIEDDATE" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."SALESTERRITORY" MODIFY ("COSTLASTYEAR" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."SALESTERRITORY" MODIFY ("COSTYTD" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."SALESTERRITORY" MODIFY ("SALESLASTYEAR" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."SALESTERRITORY" MODIFY ("SALESYTD" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."SALESTERRITORY" MODIFY ("GROUPS" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."SALESTERRITORY" MODIFY ("COUNTRYREGÝONCODE" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."SALESTERRITORY" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."SALESTERRITORY" MODIFY ("TERRITORYID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STORE
--------------------------------------------------------

  ALTER TABLE "BILGEADAM"."STORE" MODIFY ("MODIFIEDDATE" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."STORE" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "BILGEADAM"."STORE" MODIFY ("BUSINESSENTITYID" NOT NULL ENABLE);
